language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
- '8'
- '10'
os:
- linux
# - osx
matrix:
  fast_finish: true
env:
  matrix:
  - CXX=g++-4.8
  global:
  # NPM KEY
  - secure: "Fb5nL+K+Xb2G7JdEaJWFhBbOXP48NErPL+ZBeSf0EGJSaoDUgki7d4qXYaLgRgdzHNHhp6ggVTHRzkjyx1L3r6kn8Z6MuwHOSRcTTUb7Rq2+DgNMTA8Qd8eqBnNpazJDvb+9+5c7zqF5duwrRYmjaiM0mIkb1b4bkWMzMGwacbN7uHdZHcp4PkNur+VsVpQnqW/JGA6oOVwUw1RuPBFqw/pfzYMZPFZfnJsFKYl2VGpaAsxwhxwJ9Rdc0PzqYoWuWVQnnU/9dvdo85JcwrYnJ/zn8AorKEa/RfKv7XYGTtXcPcgUQDzqogwNDEdq49ptb3O0TNZI7QaMNB2JIAlc1B2qNnANeAzX5FaPVMtkSpGquv0r54LdaC2+DizauanGHN9GBij5jHGktWHv+gqGi5DYlSjA3dmVk5PZ9cSPHddQAZollI6qTU2KHno+7/4xQdA+uqudI8LXYu8nY+HYbkFyujJA9SenXH7WFY0WGGjxMW67p0jNbA+sL9f0FOJxZtjYlD4CbDZSPrhSDbuZvnQBvpnf5D8lVETbPlxk6/COIWxWr8B/2svcurUWhdntJe2x7SaNuv1xjOuMLLdrV/TrMR7HGq+Xx3W0q2cstQgfuTS55FwtLjlxgJKDDC+4CX/rT9zGzzg3a9iE/BNDbISgcL0xlAWMd4+CXjWymtk="
script: ./scripts/build.sh
after_success:
- npm run coverage
before_deploy:
- npm prune --production
- tar -czvf pactjs.tar.gz config dist src package.json README.md LICENSE
- npm run deploy:prepare
deploy:
- provider: releases
  api_key:
    secure: FmoLJnO8GNxyztR2P433ZCumYPrxiZdBCfVhmhTGYlXhOfVaAECm0gUVPLZuBQRUaqsef5ekg+OSIA5xbrnNoOQ9qlmnF2n+5yiwqG6o35XLA4L6lB5pL+x8xoAAgpaj9dTD184HKGdub3heQStTPRd2ll3nNRwxhfyIyBaMX3elDTH3mkV2QxNhG1RTgJe322PQrwoU2sWkghTWNr4t+h/G+oYu364xwZuxFX1hrFpAW+IEmbDSuhmCe24lMU96ntIiciRU3eBYR7s3KlktOFgMORXMRw3H/qaGmx7rKtpJ892XGRuVbw+tPB3A1jbFvOwJwzpnsWG5REu3PkZ6oiWpnX+5riN3jPyvFpWd+LLfH1KdZeBnF/anEfl+mSPdrDROOWotV3Xt5zOiEwx2j4BRbDNfa6wXzX0zK31AMf0IFmw7KZJkzcyWjNRluxTn3r2bbjNoi+gBojQuX27R3AQz5G0E0yZUk5ujmcd+85WOgNh/zVwsZLHYVQxDyULkbDTCDAulBsJLyxUFRs0JixyHCvA6srrUdpcO0NdyDfvULk9e/g/c9aD56Rk4xT4/Xa7K1fAHLjLkV6CA4H9Of96Zl2BK8r6LAlw382hO7FaZH+A3YShObEeTiZsDbfSQrFl5x8aimvc9oeYopvvQ+EdZxHvvwxHQIp/MWOybdJ4=
  file: pactjs.tar.gz
  skip_cleanup: true
  on:
    tags: true
    branch: feat/message-pact
    node: '8'
- provider: script
  skip_cleanup: true
  script: ./scripts/publish.sh
  on:
    tags: true
    branch: feat/message-pact
    node: '8'
