language: node_js
node_js:
- '4'
- '5'
- '6'
matrix:
  fast_finish: true
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: ju30KDpSYrw+nd2MmZTOjCTJu+gFNDy9auc6h/K9HhWgGX9zQ2cX0Vq4LX5EHWCImyPoVuyuxiouHoWB/eYcDtyDUoXb+EzNn/i+JXVWteQVRdbgnbDNHccGIpMYwEBrslg+iZWz5/SuxeqB/R0jd7MDK6oQBhWKAXgEYNOBEnRh814jryf93gQc8s4gONq2QoSiFk5QwDfqbvoK2o/4RsGGu3YBxy9/O8LhPTiI9YpdtjxmQtdgbchXLU0/oxv/7P/Etc5Z/0uqRwuF6YMZhJE6FT4ytLCDjaldYyMUAQ2YCT13UfouOO2gZYG0w+zpVGJ+e0hi/+6y1BCew/qNwTylMapcMpMCOsc2XLLD0HZoDrYprx8nUjZd0X859Rod+AWWEQnUhtFR7vqv69zwaH5TFR6l9uh+TragdgWUhJvWvupl1i26JBh0G1dFfWaU+rK/bmcsHK2ioPz2Ij+XrEdJV4KFtc7HPDWV1nCmiX5LA+cypDdfCNQehIufe6gArUUsV/vwtyEkTeOwzJAFgvOgufeZSivhttm/loalD1kX1JLrdR1ebxARvK2zSszeBYlFBwGCuK6sWup5Ace5TX39Ff6TRyO3YCTzaOd6k4w+Fsk93SkKLhGrDby21yIcmrkPdpDLjvR70SLb+OepemISktQpeMPrBTdfQU3J5G4=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script: npm run dist
after_success:
- npm run coverage
before_deploy:
- npm prune --production
- tar -czvf pactjs.tar.gz config dist src package.json README.md LICENSE
deploy:
- provider: releases
  api_key:
    secure: FmoLJnO8GNxyztR2P433ZCumYPrxiZdBCfVhmhTGYlXhOfVaAECm0gUVPLZuBQRUaqsef5ekg+OSIA5xbrnNoOQ9qlmnF2n+5yiwqG6o35XLA4L6lB5pL+x8xoAAgpaj9dTD184HKGdub3heQStTPRd2ll3nNRwxhfyIyBaMX3elDTH3mkV2QxNhG1RTgJe322PQrwoU2sWkghTWNr4t+h/G+oYu364xwZuxFX1hrFpAW+IEmbDSuhmCe24lMU96ntIiciRU3eBYR7s3KlktOFgMORXMRw3H/qaGmx7rKtpJ892XGRuVbw+tPB3A1jbFvOwJwzpnsWG5REu3PkZ6oiWpnX+5riN3jPyvFpWd+LLfH1KdZeBnF/anEfl+mSPdrDROOWotV3Xt5zOiEwx2j4BRbDNfa6wXzX0zK31AMf0IFmw7KZJkzcyWjNRluxTn3r2bbjNoi+gBojQuX27R3AQz5G0E0yZUk5ujmcd+85WOgNh/zVwsZLHYVQxDyULkbDTCDAulBsJLyxUFRs0JixyHCvA6srrUdpcO0NdyDfvULk9e/g/c9aD56Rk4xT4/Xa7K1fAHLjLkV6CA4H9Of96Zl2BK8r6LAlw382hO7FaZH+A3YShObEeTiZsDbfSQrFl5x8aimvc9oeYopvvQ+EdZxHvvwxHQIp/MWOybdJ4=
  file: pactjs.tar.gz
  skip_cleanup: true
  on:
    tags: true
    node: '6'
- provider: npm
  email: "tarcio@gmail.com"
  api_key:
    secure: KgY7CzHE8ZoMh0aYCG/bIw2W2PWn9gnprbah7fRYq5Iia0EyH2ZGkQCcJNrUetODuDPV5r4Yr+v6FaNmd4TvQZfSoUFXJMW2k98lN3riFVuph6o7XksB6FSqxyf7oZ19RUjs9SmzADJTmLjQIHkQB0lmrf4yiR2OhuEsKsJQB4pGCv0+q/2DBloqapByu1vijPskMtvYdbyvV7k06LzLTmf7Kh6zSBJtL4Ip5LL2hjiAHVU36lYzmd+BeEbhUlPLAjfAHQtwRiQrmAYMGYoppmhiCfrP7EyBJ9XS9p8j+EEON/K9vKoqD5Mhxff57Ou+YNXaIJXAOLpFzJc2OgiKsNTPQZmuZlObuUMA0ah71cWfr7UyHgHq7OXIP+mxBo6onGCETYhZwcj3T8cHOmX8yv6WQueT5ccbuY8Lo413SAVapQcGwWVS1T2Ibe+F0wPi/RWhrLHVS8/hbHl7VT2EGoIKrZCicuKjsv6kciUM9W/MsUj256NVOAIw+Gt8/JbzxrMVUs2miWRLCGaFr8X2ML71IJY2XBpBalA6ej3ZEVEhCzdBIivCvZ06Td8LEEVoZtcxrXODNnt3LM1vDWyNhZMZOzK4BoCIDE5JPubMfpGjL/urEBZzONdOyL/07uKRMMdTHtz+dj5FjSC7OSK9YNe5JBFzO1aTXbNXftAwAzs=
  skip_cleanup: true
  on:
    tags: true
    node: '6'
