language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
- '8'
os:
- linux
# - osx
matrix:
  fast_finish: true
env:
  matrix:
  - CXX=g++-4.8
  global:
  # NPM KEY
  - secure: NikiOMeibEpwVk4mLdXxCDm4jknLWZQQACSwHPlotB0u9JRzlyIoJhm47uzlPnKMtCylV0DMXQo32qbuv2xTIbB0cuZqcTzJaE2pQPHpnsVOrUnOlzRF0bSyRZGY/22ELQxWgK2Jc94lWBiniHbZzLeRh/iSAShj/lmUgVRXgUg1bxjdPNDOb3A+QNMMTl8NIp9FajsOp1l+2RXOZaJZwZChMnB+jLIMk4C56onV+rTn4EvxM/6mY0tOD+fO78Qz72riAcP8CSm/POlwTd/LcKdjtV+A6udPmuetZEy+4SWRF82WsWvU9RTytkr4kgct/uD7Y1oBVS9FMMBndS0YV6GSRnz4nwSUfAGJC93cijcrBzMRJxJ8+lYDMNPmED352RfIo68Lnrp73fXii2KMbyrSDFZUxaP4BMJu2LgUTBbk1+mxcEZMwByR2ZGEZMI7XXft1t2rMLWbWd9Ppo1XlT4XsJ6sLQHdU8/XDq4Zz7s4TVUnhNSpHqRUHQlpUxsvncUo7JgLoB9VzUIA8hK6Vs6/zKvCLgTew330vjDFTQCl473OlsfuFBpqHLBc57kfWbaugvan5OW1RXUpydoptX5tmIIIfWe8XbyKKCBK+fS9LO7qQaYlsPDyjQqJ+IXBRd239odNia/ke6F9Pkvcdt2Z/NEqDtuN9azKy+LHGT8
script: ./scripts/build.sh
after_success:
- npm run coverage
before_deploy:
- npm prune --production
- tar -czvf pactjs.tar.gz config dist src package.json README.md LICENSE
- npm run deploy:prepare
deploy:
- provider: releases
  api_key:
    secure: FmoLJnO8GNxyztR2P433ZCumYPrxiZdBCfVhmhTGYlXhOfVaAECm0gUVPLZuBQRUaqsef5ekg+OSIA5xbrnNoOQ9qlmnF2n+5yiwqG6o35XLA4L6lB5pL+x8xoAAgpaj9dTD184HKGdub3heQStTPRd2ll3nNRwxhfyIyBaMX3elDTH3mkV2QxNhG1RTgJe322PQrwoU2sWkghTWNr4t+h/G+oYu364xwZuxFX1hrFpAW+IEmbDSuhmCe24lMU96ntIiciRU3eBYR7s3KlktOFgMORXMRw3H/qaGmx7rKtpJ892XGRuVbw+tPB3A1jbFvOwJwzpnsWG5REu3PkZ6oiWpnX+5riN3jPyvFpWd+LLfH1KdZeBnF/anEfl+mSPdrDROOWotV3Xt5zOiEwx2j4BRbDNfa6wXzX0zK31AMf0IFmw7KZJkzcyWjNRluxTn3r2bbjNoi+gBojQuX27R3AQz5G0E0yZUk5ujmcd+85WOgNh/zVwsZLHYVQxDyULkbDTCDAulBsJLyxUFRs0JixyHCvA6srrUdpcO0NdyDfvULk9e/g/c9aD56Rk4xT4/Xa7K1fAHLjLkV6CA4H9Of96Zl2BK8r6LAlw382hO7FaZH+A3YShObEeTiZsDbfSQrFl5x8aimvc9oeYopvvQ+EdZxHvvwxHQIp/MWOybdJ4=
  file: pactjs.tar.gz
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: '8'
- provider: script
  skip_cleanup: true
  script: ./scripts/publish.sh
  on:
    tags: true
    branch: master
    node: '8'
