language: node_js
node_js:
- '5'
- '4'
- '0.12'
- '0.10'
env:
  global:
  - secure: fl4W5In7l8UggrVkbz0kBVTk/8vE807hEqF5Q7wWSM5CCGg4zpNaY9BrOmTArhr9bARWGVj/skTh3fUzBrIQhPViKGu8Pf4FVbnVc8J1ATsCcrBm40bDISCqyPVGWGTZZ8Fy6VFTT1jpwRdkP68USey5u2CPFGhAygloyRZqSbA8RimyrVv9g+BjgRKDS2GERMnjT9FeKw+W+DJr09k7r3e9ap03xbwqgxN/C1jF46t7F+0xwoF+7NFlQPt9bwYL1BM9Ha0I1OnllM73l9KHcG3lAlhOpyiDGf2YphMwJ8hNtM+oYaXtDsINTYF2JdHClo4qceWskcK+xU+pMhw+DN0Mx+FMWAnRzLfbM6rbohZATD4ncNZlGw4oggUj7rM9g5xCSfV4j3PoA1spKoZ5C+rZz/RJT9wYaBGRfHA1XaRqS/tniMSS39SjtkmdGX6y5V1Foq+ayomRp1X3yJMw1nCWQNRDL++I5sjYowiC9FFSwMdjCSPHdulE/bt6gMMRVjypoELi7r1sAMr86pozNYyn4bJoBTkbq9KCtD0MU8MLNGog16iUrLxJ1hW+AmYhLzv6saIPKCXy3pwiObOey3hM3q2i56KSHfrvZoKsL9Z4yw96osuadGVCYQVd0tdVY4uBbk/8jbDpUvhV6Fjxs2WoAMk1sFbIr4X0klRm9Do=
  matrix:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- npm install @pact-foundation/pact-node
- npm install mitm
- npm install babel-core
- npm install minimatch
install: npm install
script: npm run dist
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
