language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.10"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
    repo_token: CODE_CLIMATE_TOKEN
before_install:
  - npm install @pact-foundation/pact-node
  - npm install mitm
install: npm install
script: npm run dist
after_success: codeclimate-test-reporter < ./coverage/lcov.info
